version: '3.8'
services:
  app:
    image: 532597438699.dkr.ecr.us-east-1.amazonaws.com/onestophomeservices:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production


  
