version: '3.8'
services:
  app:
    image: 532597438699.dkr.ecr.us-east-1.amazonaws.com/onestophomeservices:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production

  cloudflared: 
    image: cloudflare/cloudflared 
    container_name: cloudflare-tunnel 
    restart: unless-stopped 
    command: tunnel run 
    environment: 
      - TUNNEL_TOKEN=${CLOUDFLARETOKEN}
    networks: 
      - cloud
  
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy
    networks: 
      - cloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    ports:
      - '8001:81'
      - '8181:80'
      - '443:443'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
networks:
  cloud:
    name: cloud
    driver: bridge
