version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.4
jobs:
  build:  
    docker:
      - image: circleci/node:14
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/app
          paths:
            - .
  push-to-ecr:
    docker:
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_OUTPUT: json
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Build and Push Docker image to ECR
          command: |
            docker build -t "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/onestophomeservices:latest" .
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            docker push "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/onestophomeservices:latest"

workflows:
  build-and-push:
    jobs:
      - build
      - push-to-ecr:
          requires:
            - build
