version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@1.15.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - aws-ecr/install
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t onestophomeservices .
            docker tag onestophomeservices:latest onestophomeservices:latest
      - aws-ecr/login
      - run:
          name: Push Docker image to Amazon ECR
          command: docker push onestophomeservices:latest
          environment:
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_DEFAULT_REGION: us-east-1
