version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.4

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - aws-cli/install
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t onestophomeservices .
            docker tag onestophomeservices:latest onestophomeservices:latest
      - run:
          name: Log in to Amazon ECR
          command: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 532597438699.dkr.ecr.us-east-1.amazonaws.com
      - run:
          name: Push Docker image to Amazon ECR
          command: docker push 532597438699.dkr.ecr.us-east-1.amazonaws.com/onestophomeservices:latest
