version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout  
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 532597438699.dkr.ecr.us-east-1.amazonaws.com
            docker build -t onestophomeservices .
            docker tag onestophomeservices:latest 532597438699.dkr.ecr.us-east-1.amazonaws.com/onestophomeservices:latest
      - run:
          name: Push Docker image to Amazon ECR
          command: |
            docker push 532597438699.dkr.ecr.us-east-1.amazonaws.com/onestophomeservices:main